language: node_js
node_js:
  - 'node'
  - 'lts/*'
  - '8'
cache: npm
script:
  - npm run test-ci
after_success:
  - npm run report-coverage
jobs:
  include:
    - name: Lint
      node_js: 'lts/*'
      script:
        - npm run lint
      after_success:
