language: node_js
node_js:
  - 'node'
  - 'lts/*'
  - '8'
cache:
  directories:
    - 'node_modules'
before_install:
  - if [[ `npm -v` < 3 ]]; then npm i -g npm@3; fi
script:
  - npm test
  - npm run coverage
